In [21]:
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
iris = datasets.load_iris()
Ciris = np.c_[iris.data.reshape(len(iris.data), -1), iris.target.reshape(len(iris.target), -1)]
np.random.seed(987654321)
np.random.shuffle(Ciris)
shuffledIrisData = Ciris[ :, :iris.data.size//len(iris.data)].reshape(iris.data.shape)
shuffledIrisTarget = Ciris[ :, iris.data.size//len(iris.data) :].reshape(iris.target.shape)

#print (iris.data)
#print (iris.target)

nbDonneeApr=100
DonneeApr=Ciris[0:nbDonneeApr]
#print(DonneeApr)


nbDonneeDev=130
DonneeDev=Ciris[nbDonneeApr:nbDonneeDev]
#print(DonneeDev)
DonnesData=shuffledIrisTarget[nbDonneeApr:nbDonneeDev]
#print(DonnesData)

nbDonneeTest=150
DonneeTest=Ciris[nbDonneeDev:nbDonneeTest]
DonnesDataeva=shuffledIrisTarget[nbDonneeDev:nbDonneeTest]

#print(DonneeTest)









# phase d'aprentissage

In [2]:
moyenne=np.zeros(3*4).reshape(4,3)
variance=np.zeros(3*4).reshape(4,3)

for i in range(4):
    for j in range(3):
        rows=np.where(DonneeApr[:,4]==j)
        resultat=DonneeApr[rows]
        moyenne[i][j]=np.mean(resultat[:,i])

        
        
for i in range(4):
    for j in range(3):
        rows=np.where(DonneeApr[:,4]==j)
        resultat=DonneeApr[rows]
        variance[i][j]=np.std(resultat[:,i],axis=0,ddof=1)  
        
        
print("L'ensemble des moyenne \n",moyenne)
print("\nL'ensemble des variances \n",variance)

print(moyenne[0][1])


L'ensemble des moyenne 
 [[4.971875   5.82972973 6.54516129]
 [3.40625    2.75405405 3.01612903]
 [1.459375   4.16756757 5.51290323]
 [0.23125    1.28918919 2.02903226]]

L'ensemble des variances 
 [[0.32551138 0.4943373  0.53468914]
 [0.34913488 0.31849873 0.30121617]
 [0.19651705 0.45095827 0.50907886]
 [0.09651174 0.18376281 0.26980678]]
5.8297297297297295


# Phase de développement

In [3]:
def f(x, moyenne, ecart_type):
    return stats.norm.pdf(x,moyenne,ecart_type)



rows0=np.where(DonneeApr[:,4]==0)
resultat0=DonneeApr[rows0]
    
rows1=np.where(DonneeApr[:,4]==1)
resultat1=DonneeApr[rows1]

rows2=np.where(DonneeApr[:,4]==2)
resultat2=DonneeApr[rows2]


P0=len(resultat0)/nbDonneeApr

print("P Setosa = ",P0,"" )

# on calcule la moyenne d apparition des 1
P1=len(resultat1)/nbDonneeApr
print("P Versicolore ",P1)
# on calcule la moyenne d apparition des 2
P2=len(resultat2)/nbDonneeApr
print("P Verginica",P2)



P Setosa =  0.32 
P Versicolore  0.37
P Verginica 0.31


In [26]:
def Modele1Setosa(sepaleL,sepaleW,petaleL,petaleW):
    sl= f(sepaleL,moyenne[0][0],variance[0][0])
    sw= f(sepaleW,moyenne[1][0],variance[1][0])
    pl= f(petaleL,moyenne[2][0],variance[2][0]) 
    pw= f(petaleW,moyenne[3][0],variance[3][0]) 
    resultat0=sl*sw*pl*pw*P0
    return resultat0

def Modele1Versicolore(sepaleL,sepaleW,petaleL,petaleW):
    sl= f(sepaleL,moyenne[0][1],variance[0][1])
    sw= f(sepaleW,moyenne[1][1],variance[1][1])
    pl= f(petaleL,moyenne[2][1],variance[2][1]) 
    pw= f(petaleW,moyenne[3][1],variance[3][1]) 
    resultat1=sl*sw*pl*pw*P1
    return resultat1

def Modele1Verginica(sepaleL,sepaleW,petaleL,petaleW):
    sl= f(sepaleL,moyenne[0][2],variance[0][2])
    sw= f(sepaleW,moyenne[1][2],variance[1][2])
    pl= f(petaleL,moyenne[2][2],variance[2][2]) 
    pw= f(petaleW,moyenne[3][2],variance[3][2]) 
    resultat2=sl*sw*pl*pw*P2
    return resultat2


def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        sepaleL=DonneeDev[i][0]
        sepaleW=DonneeDev[i][1]
        petaleL=DonneeDev[i][2]
        petaleW=DonneeDev[i][3]
        tableau.append([Modele1Setosa(sepaleL,sepaleW,petaleL,petaleW),Modele1Versicolore(sepaleL,sepaleW,petaleL,petaleW),Modele1Verginica(sepaleL,sepaleW,petaleL,petaleW)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
#print(DonneeDev)    
tableauproba1=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba1),"% pour le modele 1" )    
    

le pourcentage d'erreur est de :  13.333333333333334 % pour le modele 1


In [5]:
def Modele1Setosa(sepaleL,sepaleW,petaleL):
    sl= f(sepaleL,moyenne[0][0],variance[0][0])
    sw= f(sepaleW,moyenne[1][0],variance[1][0])
    pl= f(petaleL,moyenne[2][0],variance[2][0]) 
    resultat=sl*sw*pl*P0
    return resultat

def Modele1Versicolore(sepaleL,sepaleW,petaleL):
    sl= f(sepaleL,moyenne[0][1],variance[0][1])
    sw= f(sepaleW,moyenne[1][1],variance[1][1])
    pl= f(petaleL,moyenne[2][1],variance[2][1]) 
    resultat=sl*sw*pl*P1
    return resultat

def Modele1Verginica(sepaleL,sepaleW,petaleL):
    sl= f(sepaleL,moyenne[0][2],variance[0][2])
    sw= f(sepaleW,moyenne[1][2],variance[1][2])
    pl= f(petaleL,moyenne[2][2],variance[2][2]) 
    resultat=sl*sw*pl*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        sepaleL=DonneeDev[i][0]
        sepaleW=DonneeDev[i][1]
        petaleL=DonneeDev[i][2]
        tableau.append([Modele1Setosa(sepaleL,sepaleW,petaleL),Modele1Versicolore(sepaleL,sepaleW,petaleL),Modele1Verginica(sepaleL,sepaleW,petaleL)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
    
tableauproba2=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba2),"% pour le modele 2" ) 

le pourcentage d'erreur est de :  16.666666666666664 % pour le modele 2


In [6]:
def Modele1Setosa(sepaleL,sepaleW,petaleW):
    sl= f(sepaleL,moyenne[0][0],variance[0][0])
    sw= f(sepaleW,moyenne[1][0],variance[1][0])
    pw= f(petaleW,moyenne[3][0],variance[3][0]) 
    resultat=sl*sw*pw*P0
    return resultat

def Modele1Versicolore(sepaleL,sepaleW,petaleW):
    sl= f(sepaleL,moyenne[0][1],variance[0][1])
    sw= f(sepaleW,moyenne[1][1],variance[1][1])
    pw= f(petaleW,moyenne[3][1],variance[3][1]) 
    resultat=sl*sw*pw*P1
    return resultat

def Modele1Verginica(sepaleL,sepaleW,petaleW):
    sl= f(sepaleL,moyenne[0][2],variance[0][2])
    sw= f(sepaleW,moyenne[1][2],variance[1][2])
    pw= f(petaleW,moyenne[3][2],variance[3][2]) 
    resultat=sl*sw*pw*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        sepaleL=DonneeDev[i][0]
        sepaleW=DonneeDev[i][1]
        petaleW=DonneeDev[i][3]
        tableau.append([Modele1Setosa(sepaleL,sepaleW,petaleW),Modele1Versicolore(sepaleL,sepaleW,petaleW),Modele1Verginica(sepaleL,sepaleW,petaleW)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
    
tableauproba3=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba3),"% pour le modele 3" ) 

le pourcentage d'erreur est de :  13.333333333333334 % pour le modele 3


In [7]:
def Modele1Setosa(sepaleL,petaleL,petaleW):
    sl= f(sepaleL,moyenne[0][0],variance[0][0])
    pl= f(petaleL,moyenne[2][0],variance[2][0]) 
    pw= f(petaleW,moyenne[3][0],variance[3][0]) 
    resultat=sl*pl*pw*P0
    return resultat

def Modele1Versicolore(sepaleL,petaleL,petaleW):
    sl= f(sepaleL,moyenne[0][1],variance[0][1])
    pl= f(petaleL,moyenne[2][1],variance[2][1]) 
    pw= f(petaleW,moyenne[3][1],variance[3][1]) 
    resultat=sl*pl*pw*P1
    return resultat

def Modele1Verginica(sepaleL,petaleL,petaleW):
    sl= f(sepaleL,moyenne[0][2],variance[0][2])
    pl= f(petaleL,moyenne[2][2],variance[2][2]) 
    pw= f(petaleW,moyenne[3][2],variance[3][2]) 
    resultat=sl*pl*pw*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        sepaleL=DonneeDev[i][0]
        sepaleW=DonneeDev[i][1]
        petaleL=DonneeDev[i][2]
        petaleW=DonneeDev[i][3]
        tableau.append([Modele1Setosa(sepaleL,petaleL,petaleW),Modele1Versicolore(sepaleL,petaleL,petaleW),Modele1Verginica(sepaleL,petaleL,petaleW)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
    
tableauproba4=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba4),"% pour le modele 4" ) 

le pourcentage d'erreur est de :  10.0 % pour le modele 4


In [8]:
def Modele1Setosa(sepaleW,petaleL,petaleW):
    sw= f(sepaleW,moyenne[1][0],variance[1][0])
    pl= f(petaleL,moyenne[2][0],variance[2][0]) 
    pw= f(petaleW,moyenne[3][0],variance[3][0]) 
    resultat=sw*pl*pw*P0
    return resultat

def Modele1Versicolore(sepaleW,petaleL,petaleW):
    sw= f(sepaleW,moyenne[1][1],variance[1][1])
    pl= f(petaleL,moyenne[2][1],variance[2][1]) 
    pw= f(petaleW,moyenne[3][1],variance[3][1]) 
    resultat=sw*pl*pw*P1
    return resultat

def Modele1Verginica(sepaleW,petaleL,petaleW):
    sw= f(sepaleW,moyenne[1][2],variance[1][2])
    pl= f(petaleL,moyenne[2][2],variance[2][2]) 
    pw= f(petaleW,moyenne[3][2],variance[3][2]) 
    resultat=sw*pl*pw*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        sepaleW=DonneeDev[i][1]
        petaleL=DonneeDev[i][2]
        petaleW=DonneeDev[i][3]
        tableau.append([Modele1Setosa(sepaleW,petaleL,petaleW),Modele1Versicolore(sepaleW,petaleL,petaleW),Modele1Verginica(sepaleW,petaleL,petaleW)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
    
tableauproba5=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba5),"% pour le modele 5" ) 

le pourcentage d'erreur est de :  13.333333333333334 % pour le modele 5


In [9]:
def Modele1Setosa(sepaleL,sepaleW):
    sl= f(sepaleL,moyenne[0][0],variance[0][0])
    sw= f(sepaleW,moyenne[1][0],variance[1][0])
    resultat=sl*sw*P0
    return resultat

def Modele1Versicolore(sepaleL,sepaleW):
    sl= f(sepaleL,moyenne[0][1],variance[0][1])
    sw= f(sepaleW,moyenne[1][1],variance[1][1])
    resultat=sl*sw*P1
    return resultat

def Modele1Verginica(sepaleL,sepaleW):
    sl= f(sepaleL,moyenne[0][2],variance[0][2])
    sw= f(sepaleW,moyenne[1][2],variance[1][2])
    resultat=sl*sw*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        sepaleL=DonneeDev[i][0]
        sepaleW=DonneeDev[i][1]
        tableau.append([Modele1Setosa(sepaleL,sepaleW),Modele1Versicolore(sepaleL,sepaleW,),Modele1Verginica(sepaleL,sepaleW)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
    
tableauproba6=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba6),"% pour le modele 6" ) 

le pourcentage d'erreur est de :  20.0 % pour le modele 6


In [10]:
def Modele1Setosa(petaleL,petaleW):
   
    pl= f(petaleL,moyenne[2][0],variance[2][0]) 
    pw= f(petaleW,moyenne[3][0],variance[3][0]) 
    resultat=pl*pw*P0
    return resultat

def Modele1Versicolore(petaleL,petaleW):
  
    pl= f(petaleL,moyenne[2][1],variance[2][1]) 
    pw= f(petaleW,moyenne[3][1],variance[3][1]) 
    resultat=pl*pw*P1
    return resultat

def Modele1Verginica(petaleL,petaleW):
   
    pl= f(petaleL,moyenne[2][2],variance[2][2]) 
    pw= f(petaleW,moyenne[3][2],variance[3][2]) 
    resultat=pl*pw*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
       
        petaleL=DonneeDev[i][2]
        petaleW=DonneeDev[i][3]
        tableau.append([Modele1Setosa(petaleL,petaleW),Modele1Versicolore(petaleL,petaleW),Modele1Verginica(petaleL,petaleW)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
    
tableauproba7=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba7),"% pour le modele 7" ) 

le pourcentage d'erreur est de :  13.333333333333334 % pour le modele 7


In [11]:
def Modele1Setosa(sepaleW,petaleL):
    sw= f(sepaleW,moyenne[1][0],variance[1][0])
    pl= f(petaleL,moyenne[2][0],variance[2][0]) 
    resultat=sw*pl*P0
    return resultat

def Modele1Versicolore(sepaleW,petaleL):
    sw= f(sepaleW,moyenne[1][1],variance[1][1])
    pl= f(petaleL,moyenne[2][1],variance[2][1]) 
    resultat=sw*pl*P1
    return resultat

def Modele1Verginica(sepaleW,petaleL):
    sw= f(sepaleW,moyenne[1][2],variance[1][2])
    pl= f(petaleL,moyenne[2][2],variance[2][2])  
    resultat=sw*pl*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        sepaleW=DonneeDev[i][1]
        petaleL=DonneeDev[i][2]
        tableau.append([Modele1Setosa(sepaleW,petaleL),Modele1Versicolore(sepaleW,petaleL),Modele1Verginica(sepaleW,petaleL)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
    
tableauproba8=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba8),"% pour le modele 8" )    

le pourcentage d'erreur est de :  10.0 % pour le modele 8


In [12]:
def Modele1Setosa(sepaleL,petaleW):
    sl= f(sepaleL,moyenne[0][0],variance[0][0])
    pw= f(petaleW,moyenne[3][0],variance[3][0]) 
    resultat=sl*pw*P0
    return resultat

def Modele1Versicolore(sepaleL,petaleW):
    sl= f(sepaleL,moyenne[0][1],variance[0][1])
    pw= f(petaleW,moyenne[3][1],variance[3][1]) 
    resultat=sl*pw*P1
    return resultat

def Modele1Verginica(sepaleL,petaleW):
    sl= f(sepaleL,moyenne[0][2],variance[0][2])
    pw= f(petaleW,moyenne[3][2],variance[3][2]) 
    resultat=sl*pw*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        sepaleL=DonneeDev[i][0]
        petaleW=DonneeDev[i][3]
        tableau.append([Modele1Setosa(sepaleL,petaleW),Modele1Versicolore(sepaleL,petaleW),Modele1Verginica(sepaleL,petaleW)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
    
tableauproba9=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba9),"% pour le modele 9" ) 

le pourcentage d'erreur est de :  10.0 % pour le modele 9


In [13]:
def Modele1Setosa(sepaleW,petaleW):
    sw= f(sepaleW,moyenne[1][0],variance[1][0])
    pw= f(petaleW,moyenne[3][0],variance[3][0]) 
    resultat=sw*pw*P0
    return resultat

def Modele1Versicolore(sepaleW,petaleW):
    sw= f(sepaleW,moyenne[1][1],variance[1][1])
    pw= f(petaleW,moyenne[3][1],variance[3][1]) 
    resultat=sw*pw*P1
    return resultat

def Modele1Verginica(sepaleW,petaleW):
    sw= f(sepaleW,moyenne[1][2],variance[1][2])
    pw= f(petaleW,moyenne[3][2],variance[3][2]) 
    resultat=sw*pw*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        sepaleW=DonneeDev[i][1]
        petaleW=DonneeDev[i][3]
        tableau.append([Modele1Setosa(sepaleW,petaleW),Modele1Versicolore(sepaleW,petaleW),Modele1Verginica(sepaleW,petaleW)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
    
tableauproba10=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba10),"% pour le modele 10" ) 

le pourcentage d'erreur est de :  10.0 % pour le modele 10


In [14]:
def Modele1Setosa(sepaleL,petaleL):
    sl= f(sepaleL,moyenne[0][0],variance[0][0])
    pl= f(petaleL,moyenne[2][0],variance[2][0]) 
    resultat=sl*pl*P0
    return resultat

def Modele1Versicolore(sepaleL,petaleL):
    sl= f(sepaleL,moyenne[0][1],variance[0][1])
    pl= f(petaleL,moyenne[2][1],variance[2][1]) 
    resultat=sl*pl*P1
    return resultat

def Modele1Verginica(sepaleL,petaleL):
    sl= f(sepaleL,moyenne[0][2],variance[0][2])
    pl= f(petaleL,moyenne[2][2],variance[2][2]) 
    resultat=sl*pl*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        sepaleL=DonneeDev[i][0]
        petaleL=DonneeDev[i][2]
        tableau.append([Modele1Setosa(sepaleL,petaleL),Modele1Versicolore(sepaleL,petaleL),Modele1Verginica(sepaleL,petaleL)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
    
tableauproba11=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba11),"% pour le modele 11" ) 

le pourcentage d'erreur est de :  13.333333333333334 % pour le modele 11


In [15]:
def Modele1Setosa(sepaleL):
    sl= f(sepaleL,moyenne[0][0],variance[0][0])
    resultat=sl*P0
    return resultat

def Modele1Versicolore(sepaleL):
    sl= f(sepaleL,moyenne[0][1],variance[0][1])
    resultat=sl*P1
    return resultat

def Modele1Verginica(sepaleL):
    sl= f(sepaleL,moyenne[0][2],variance[0][2])
    
    resultat=sl*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        sepaleL=DonneeDev[i][0]
        tableau.append([Modele1Setosa(sepaleL),Modele1Versicolore(sepaleL),Modele1Verginica(sepaleL)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
    
tableauproba12=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba12),"% pour le modele 12" ) 

le pourcentage d'erreur est de :  26.666666666666668 % pour le modele 12


In [16]:
def Modele1Setosa(sepaleW):
    sw= f(sepaleW,moyenne[1][0],variance[1][0])
    resultat=sw*P0
    return resultat

def Modele1Versicolore(sepaleW,):
    sw= f(sepaleW,moyenne[1][1],variance[1][1])
    resultat=sw*P1
    return resultat

def Modele1Verginica(sepaleW):
    sw= f(sepaleW,moyenne[1][2],variance[1][2])
    resultat=sw*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        sepaleW=DonneeDev[i][1]
        tableau.append([Modele1Setosa(sepaleW),Modele1Versicolore(sepaleW),Modele1Verginica(sepaleW)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    return (nb_erreur/30)*100
    
tableauproba13=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba13),"% pour le modele 13" ) 

le pourcentage d'erreur est de :  46.666666666666664 % pour le modele 13


In [17]:
def Modele1Setosa(petaleL):
    pl= f(petaleL,moyenne[2][0],variance[2][0])   
    resultat=pl*P0
    return resultat

def Modele1Versicolore(petaleL):
    pl= f(petaleL,moyenne[2][1],variance[2][1]) 
    resultat=pl*P1
    return resultat

def Modele1Verginica(petaleL):
    pl= f(petaleL,moyenne[2][2],variance[2][2]) 
    resultat=pl*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        petaleL=DonneeDev[i][2]
        tableau.append([Modele1Setosa(petaleL),Modele1Versicolore(petaleL),Modele1Verginica(petaleL)])
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100

   
tableauproba14=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba14),"% pour le modele 14" ) 

le pourcentage d'erreur est de :  6.666666666666667 % pour le modele 14


In [18]:
def Modele1Setosa(petaleW):
    pw= f(petaleW,moyenne[3][0],variance[3][0]) 
    resultat=pw*P0
    return resultat

def Modele1Versicolore(petaleW): 
    pw= f(petaleW,moyenne[3][1],variance[3][1]) 
    resultat=pw*P1
    return resultat

def Modele1Verginica(petaleW):
    pw= f(petaleW,moyenne[3][2],variance[3][2]) 
    resultat=pw*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(30):
        petaleW=DonneeDev[i][3]
        tableau.append([Modele1Setosa(petaleW),Modele1Versicolore(petaleW),Modele1Verginica(petaleW)])
    #print(tableau)
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(30):
        if DonnesData[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/30)*100
    
tableauproba15=tableauRecapitulatif()    
    
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba15),"% pour le modele 15" ) 

le pourcentage d'erreur est de :  10.0 % pour le modele 15


In [19]:
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba1),"% pour le modele 1" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba2),"% pour le modele 2" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba3),"% pour le modele 3" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba4),"% pour le modele 4" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba5),"% pour le modele 5" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba6),"% pour le modele 6" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba7),"% pour le modele 7" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba8),"% pour le modele 8" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba9),"% pour le modele 9" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba10),"% pour le modele 10" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba11),"% pour le modele 11" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba12),"% pour le modele 12" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba13),"% pour le modele 13" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba14),"% pour le modele 14" ) 
print("le pourcentage d'erreur est de : ",pour_erreure(tableauproba15),"% pour le modele 15" ) 



le pourcentage d'erreur est de :  13.333333333333334 % pour le modele 1
le pourcentage d'erreur est de :  16.666666666666664 % pour le modele 2
le pourcentage d'erreur est de :  13.333333333333334 % pour le modele 3
le pourcentage d'erreur est de :  10.0 % pour le modele 4
le pourcentage d'erreur est de :  13.333333333333334 % pour le modele 5
le pourcentage d'erreur est de :  20.0 % pour le modele 6
le pourcentage d'erreur est de :  13.333333333333334 % pour le modele 7
le pourcentage d'erreur est de :  10.0 % pour le modele 8
le pourcentage d'erreur est de :  10.0 % pour le modele 9
le pourcentage d'erreur est de :  10.0 % pour le modele 10
le pourcentage d'erreur est de :  13.333333333333334 % pour le modele 11
le pourcentage d'erreur est de :  26.666666666666668 % pour le modele 12
le pourcentage d'erreur est de :  46.666666666666664 % pour le modele 13
le pourcentage d'erreur est de :  6.666666666666667 % pour le modele 14
le pourcentage d'erreur est de :  10.0 % pour le modele 15

# Phase d'évaluation

In [20]:
def Modele1Setosa(petaleL):
    pl= f(petaleL,moyenne[2][0],variance[2][0])   
    resultat=pl*P0
    return resultat

def Modele1Versicolore(petaleL):
    pl= f(petaleL,moyenne[2][1],variance[2][1]) 
    resultat=pl*P1
    return resultat

def Modele1Verginica(petaleL):
    pl= f(petaleL,moyenne[2][2],variance[2][2]) 
    resultat=pl*P2
    return resultat

def tableauRecapitulatif():
    tableau=[]
    for i in range(20):
        petaleL=DonneeTest[i][2]
        tableau.append([Modele1Setosa(petaleL),Modele1Versicolore(petaleL),Modele1Verginica(petaleL)])
    return(tableau)


def pour_erreure(tab):
    nb_erreur=0
    for i in range(20):
        if DonnesDataeva[i] != np.argmax(tab[i]):
            nb_erreur+=1
    
    return (nb_erreur/20)*100

   
tableauproba=tableauRecapitulatif()    
    
print("le pourcentage d'erreur de la phase d'evaluation est de  : ",pour_erreure(tableauproba),"% " ) 

le pourcentage d'erreur de la phase d'evaluation est de  :  15.0 % 
